Repository jullaene/walkmong_front, pull requests merged in 2024-12, with the labels that each got.

#68 [Chore] 컴포넌트 모듈화
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong/Extension/Labels.swift
  walkmong/walkmong/Extension/NavigationBar.swift
  walkmong/walkmong/Extension/UIButton+.swift
  walkmong/walkmong/Info.plist
  walkmong/walkmong/MatchingApplyProcedure/Views/DayCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMessageView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/PlaceSearchResultCollectionViewCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/Mypage/Views/SocialInfoView.swift
  walkmong/walkmong/SceneDelegate.swift
Labels: Chore 📂

#66 [Feat] 자잘한 설정 수정
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong/Info.plist
  walkmong/walkmong/SceneDelegate.swift
Labels: Feature ✨

#71 [Chore] optional binding
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CalendarView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DayCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DropdownView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkInfoView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Views/BasicInfoView.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
  walkmong/walkmong/Mypage/Views/SocialInfoView.swift
  walkmong/walkmong/Mypage/Views/VaccinationView.swift
Labels: Chore 📂

#74 [Feat] 알림 버튼 추가
  walkmong/walkmong/Assets.xcassets/MatchingView/alertIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/alertIcon.imageset/alertIcon.svg
  walkmong/walkmong/Extension/UIButton+.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
Labels: Feature ✨

#81 [Fix] dog review UI 수정
  walkmong/walkmong/Extension/UIButton+.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CircleTagView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileFrameView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkReviewCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkReviewFrame.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkReviewView.swift
Labels: Fix 🔨

#84 [Design] my page
  walkmong/Podfile
  walkmong/Podfile.lock
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageCheckVerified.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageCheckVerified.imageset/MyPageCheckVerified.svg
  walkmong/walkmong/Assets.xcassets/MyPage/MyPagePlusIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/MyPagePlusIcon.imageset/MyPagePlusIcon.svg
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageReviewArrow.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageReviewArrow.imageset/MyPageReviewArrow.svg
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageSettingsArrow.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageSettingsArrow.imageset/MyPageSettingsArrow.svg
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageStarIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/MyPageStarIcon.imageset/MyPageStarIcon.svg
  walkmong/walkmong/Assets.xcassets/MyPage/ProfileArrow.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/ProfileArrow.imageset/ProfileArrow.svg
  walkmong/walkmong/Assets.xcassets/MyPage/defaultProfileImage.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/defaultProfileImage.imageset/defaultProfileImage.png
  walkmong/walkmong/Extension/UIImage+.swift
  walkmong/walkmong/Extension/UIImageView+.swift
  walkmong/walkmong/Extension/UILabel+.swift
  walkmong/walkmong/Extension/UIView+.swift
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkReviewCell.swift
  walkmong/walkmong/Mypage/Controllers/MyPageViewController.swift
  walkmong/walkmong/Mypage/Views/CustomRadarChartView.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
  walkmong/walkmong/Mypage/Views/MyPageContentViewSection.swift
  walkmong/walkmong/Mypage/Views/MyPagePetView.swift
  walkmong/walkmong/Mypage/Views/MyPageProfileView.swift
  walkmong/walkmong/Mypage/Views/MyPageReviewView.swift
  walkmong/walkmong/Mypage/Views/MyPageSettingsView.swift
  walkmong/walkmong/Mypage/Views/MyPageView.swift
  walkmong/walkmong/Mypage/Views/MyPageWalkInfoView.swift
  walkmong/walkmong/Mypage/Views/PetProfileCell.swift
  walkmong/walkmong/Mypage/Views/VaccinationView.swift
Labels: Design 🎨

#90 [Feat] Report view UI
  walkmong/walkmong/Global/Components/NavigationBar.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/MyPage/myPageReportChecked.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MyPage/myPageReportChecked.imageset/myPageReportUnchecked.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MyPage/myPageReportUnchecked.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MyPage/myPageReportUnchecked.imageset/myPageReportChecked.svg
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/ProfileFrameView.swift
  walkmong/walkmong/Presentation/MyPage/MyPageReport/ViewController/MyPageReportViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPageReport/Views/MyPageReportView.swift
  walkmong/walkmong/Presentation/MyPage/MyPageReport/Views/ReportTextView.swift
  walkmong/walkmong/Presentation/MyPage/MyPageReport/Views/ResonButtonView.swift
Labels: Feature ✨, Design 🎨

#93 [Feat] mypageownerreviewvc 구현
  walkmong/walkmong/Global/Components/CharacterCountManager.swift
  walkmong/walkmong/Global/Extension/UIButton+.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/MatchingDogInformationView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/FilterView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewCell.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageReviewView.swift
  walkmong/walkmong/Presentation/MyPage/MyPageOwnerReview/ViewController/MyPageOwnerReviewViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPageOwnerReview/Views/MyPageOwnerReviewView.swift
Labels: Feature ✨, Fix 🔨, Design 🎨

#102 [Design] 워크톡 채팅방 목록 UI 구현
  .gitignore
  walkmong/walkmong/Global/Components/MatchingState.swift
  walkmong/walkmong/Global/Extension/String+.swift
  walkmong/walkmong/Global/Extension/UIColor+.swift
  walkmong/walkmong/Global/Extension/UIImageView+.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/Send.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/Send.imageset/send-03.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/Union.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/Union.imageset/Union.svg
  walkmong/walkmong/Presentation/Walktalk/Chat/Models/WalkTalkChatLogModel.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/ViewController/WalktalkChatViewController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatDateHeaderView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageReceivedCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageSentCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatUpperView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatView.swift
  walkmong/walkmong/Presentation/Walktalk/List/Models/WalktalkListModel.swift
  walkmong/walkmong/Presentation/Walktalk/List/ViewController/WalktalkListViewController.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListMatchingStateCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListPageCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListTabBarCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListView.swift
Labels: Design 🎨

#108 [Design] 워크톡 UI 구현
  walkmong/walkmong/Global/Extension/String+.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Models/WalkTalkChatLogModel.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatDateHeaderView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageReceivedCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageSentCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatUpperView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatView.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListMatchingCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListTapBarCollectionViewCell.swift
Labels: Design 🎨

#106 [Feat] Alert UI
  walkmong/walkmong/Global/Components/NavigationBar.swift
  walkmong/walkmong/Presentation/MatchingApply/Alert/ViewController/AlertViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Alert/Views/AlertCell.swift
  walkmong/walkmong/Presentation/MatchingApply/Alert/Views/AlertView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageView.swift
Labels: Feature ✨, Design 🎨

#110 [Fix] string style
  walkmong/walkmong/Network/API/DogAPI.swift
  walkmong/walkmong/Network/Manager/NetworkManager.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingCell.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Models/MyPagePetModel.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/ViewController/MyPageViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageContentViewSection.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPagePetView.swift
Labels: Fix 🔨

#111 [Fix] walk review view
  walkmong/walkmong/Global/Components/NavigationBar.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/ViewController/PhotoViewerViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/ViewController/WalkReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewCell.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewTotalRatingView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewView.swift
Labels: Fix 🔨

#112 [Fix] radar chart
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/CustomRadarChartView.swift
Labels: Fix 🔨

#118 [Refactor] 네트워크 매니저 및 API 구현부 리팩토링
  walkmong/walkmong/Network/API/DogAPI.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Foundation/NetworkProvider.swift
  walkmong/walkmong/Network/Manager/AuthManager.swift
  walkmong/walkmong/Network/Manager/KeychainManager.swift
  walkmong/walkmong/Network/Manager/NetworkManager.swift
  walkmong/walkmong/Network/Response/APIResponse.swift
  walkmong/walkmong/Network/Response/DogInfoResponse.swift
  walkmong/walkmong/Network/Response/DogListResponse.swift
  walkmong/walkmong/Network/Service/DogService.swift
Labels: Refactor

#116 [Design/Feat] 공통 AlertView 구현
  walkmong/walkmong/Presentation/AlertView/CustomAlertViewController.swift
Labels: Feature ✨, Design 🎨

#121 [Refactor] SecretManager 메소드 추상화
  walkmong/walkmong/Application/AppDelegate.swift
  walkmong/walkmong/Network/API/BoardAPI.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Manager/GeocodingAPIManager.swift
  walkmong/walkmong/Network/Manager/ReverseGeocodingAPIManager.swift
  walkmong/walkmong/Network/Manager/SecretManager.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/ViewController/MatchingViewController.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/ViewController/DogProfileViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPagePetView.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListTapBarCollectionViewCell.swift
Labels: Refactor

#124 [Refactor] KeyboardEventManager 구현
  walkmong/walkmong/Application/AppDelegate.swift
  walkmong/walkmong/Global/Components/KeyboardEventManager.swift
  walkmong/walkmong/Global/Extension/UIViewController+.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Service/DogService.swift
  walkmong/walkmong/Presentation/MatchingApply/Map/ViewController/MatchingApplyMapViewController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/ViewController/WalktalkChatViewController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageReceivedCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatMessageSentCollectionViewCell.swift
Labels: Refactor
