Repository jullaene/walkmong_front, pull requests merged in 2024-11, with the labels that each got.

#4 [Chore] ViewController 파일 추가
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyDetailCheckViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyFinalViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyMessageViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingViewController.swift
  walkmong/walkmong/MatchingState/MatchingProgressMapViewController.swift
  walkmong/walkmong/MatchingState/MatchingProgressViewController.swift
  walkmong/walkmong/Mypage/DogProfileViewController.swift
  walkmong/walkmong/Mypage/EditDogOwnershipViewController.swift
  walkmong/walkmong/Mypage/EditWalkerProfileViewController.swift
  walkmong/walkmong/SceneDelegate.swift
  walkmong/walkmong/ViewController.swift
Labels: Chore 📂

#8 [Fix] .gitignore 파일 내용 *.xcuserstate로 수정
  .gitignore
  walkmong/walkmong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Fix 🔨

#10 [Fix] .gitignore 수정 및 UserInterfaceState.xcuserstate 추적 제거
  .gitignore
  walkmong/walkmong.xcodeproj/project.xcworkspace/xcuserdata/hoyeon.xcuserdatad/UserInterfaceState.xcuserstate
Labels: Fix 🔨

#15 [Design] matching view UI 구현 완료
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/Contents.json
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MatchingApplyProcedureIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MatchingApplyProcedureIcon.imageset/MatchingApplyProcedureIcon.svg
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MatchingStateIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MatchingStateIcon.imageset/MatchingStateIcon.svg
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MypageIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/MypageIcon.imageset/MypageIcon.svg
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/WalkMongTalkIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainTabBarIcon/WalkMongTalkIcon.imageset/WalkMongTalkIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/femaleIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/femaleIcon.imageset/femaleIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/filterIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/filterIcon.imageset/filterIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/locationIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/locationIcon.imageset/locationIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/maleIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/maleIcon.imageset/maleIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/pencilIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/pencilIcon.imageset/pencilIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage.imageset/puppyImage.png
  walkmong/walkmong/Assets.xcassets/MatchingView/selectdongbtn.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/selectdongbtn.imageset/selectdongbtn.svg
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailCheckViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyFinalViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMessageViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CalendarView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DayCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
Labels: Design 🎨

#20 [Fix] 하단 탭바 디자인 수정
  walkmong/walkmong/MainTabBarController.swift
Labels: Fix 🔨

#22 [Feat] 동 선택 기능 추가
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DropdownView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
Labels: Feature ✨

#24 [Chore] ColorSet 추가 및 Provisioning Profile 수정
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong/Assets.xcassets/MainColor/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray100.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray200.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray300.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray400.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray500.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/Gray600.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/MainBlue.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/MainGreen.colorset/Contents.json
Labels: Chore 📂

#25 [Design] 산책 지원 - 산책 내용 확인 UI 구현
  walkmong/walkmong/Assets.xcassets/MainColor/LightBlue.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/MainBlack.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MainColor/PaleGreen.colorset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/ArrowRight.imageset/ArrowRight.svg
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/ArrowRight.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/CalendarIcon.imageset/CalendarIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/CalendarIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/WarningIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyProcedure/WarningIcon.imageset/NotificationIcon.svg
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/NavigationBar.swift
  walkmong/walkmong/UIView+.swift
Labels: Design 🎨

#27 [Feat] 산책 지원 - 산책 내용 확인 UI 구현
  walkmong/walkmong/Assets.xcassets/NavigationBar/BackButton.imageset/BackButton.svg
  walkmong/walkmong/Assets.xcassets/NavigationBar/BackButton.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/NavigationBar/Contents.json
  walkmong/walkmong/Assets.xcassets/NavigationBar/DeleteButton.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/NavigationBar/DeleteButton.imageset/DeleteButton.svg
  walkmong/walkmong/Assets.xcassets/NavigationBar/RefreshButton.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/NavigationBar/RefreshButton.imageset/RefreshButton.svg
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyDetailSelectModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/NavigationBar.swift
Labels: Feature ✨

#28 [Feat] 캘린더 기능 구현 완료
  walkmong/walkmong/MatchingApplyProcedure/Views/CalendarView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DayCell.swift
Labels: Feature ✨

#29 [Feat] 카테고리 필터 생성
  walkmong/walkmong.xcodeproj/xcuserdata/hoyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  walkmong/walkmong/AppDelegate.swift
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DropdownView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
Labels: Feature ✨

#32 [Design] 만남 장소 검색 UI 구현
  walkmong/walkmong/Assets.xcassets/Illustration/Contents.json
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration1.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration1.imageset/Illustration1.svg
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration2.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration2.imageset/Illustration2.svg
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration3.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration3.imageset/Illustration3.svg
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration4.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/Illustration/Illustration4.imageset/Illustration4.svg
  walkmong/walkmong/Assets.xcassets/MatchingApplyPlaceSearchView/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyPlaceSearchView/CurrentLocation.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyPlaceSearchView/CurrentLocation.imageset/CurrentLocation.svg
  walkmong/walkmong/Assets.xcassets/MatchingApplyPlaceSearchView/SearchIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingApplyPlaceSearchView/SearchIcon.imageset/SearchIcon.svg
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyPlaceSearchView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/PlaceSearchResultCollectionViewCell.swift
  walkmong/walkmong/NSObject+.swift
  walkmong/walkmong/UIViewController+.swift
Labels: Design 🎨

#34 [Fix] MatchingViewController 관련 수정 모음
  walkmong/walkmong.xcodeproj/xcuserdata/hoyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  walkmong/walkmong/AppDelegate.swift
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage01.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage01.imageset/puppyImage01.png
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage02.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage02.imageset/puppyImage02.png
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage03.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage03.imageset/puppyImage03.png
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingData.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CalendarView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DayCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DropdownView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
Labels: Fix 🔨

#37 [Design] 만남 장소 맵 UI 구현
  .gitignore
  walkmong/Podfile
  walkmong/Podfile.lock
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong.xcworkspace/contents.xcworkspacedata
  walkmong/walkmong.xcworkspace/xcshareddata/swiftpm/Package.resolved
  walkmong/walkmong/AppDelegate.swift
  walkmong/walkmong/Assets.xcassets/MapView/Contents.json
  walkmong/walkmong/Assets.xcassets/MapView/CurrentLocationIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MapView/CurrentLocationIcon.imageset/CurrentLocationIcon.svg
  walkmong/walkmong/Assets.xcassets/MapView/MarkerIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MapView/MarkerIcon.imageset/MarkerIcon.png
  walkmong/walkmong/Assets.xcassets/MapView/MarkerInfoWindow.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MapView/MarkerInfoWindow.imageset/MarkerInfoWindow.svg
  walkmong/walkmong/Extension/NSObject+.swift
  walkmong/walkmong/Extension/NavigationBar.swift
  walkmong/walkmong/Extension/ProgressBar.swift
  walkmong/walkmong/Extension/UILabel+.swift
  walkmong/walkmong/Extension/UITextField+.swift
  walkmong/walkmong/Extension/UIView+.swift
  walkmong/walkmong/Extension/UIViewController+.swift
  walkmong/walkmong/Info.plist
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/ReverseGeocodingModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CustomMarker.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapAddressModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapNotifyModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyPlaceSearchView.swift
  walkmong/walkmong/Network/ReverseGeocodingAPIManager.swift
Labels: Design 🎨, Chore 📂

#39 [Design] MatchingDoginformation UI 구현
  walkmong/walkmong/Assets.xcassets/MatchingView/locationIconBlue.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/locationIconBlue.imageset/locationIconBlue.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/meetingPlace.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/meetingPlace.imageset/meetingPlace.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/messageIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/messageIcon.imageset/messageIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/preMeeting.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/preMeeting.imageset/preMeeting.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/profileExample.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/profileExample.imageset/profileExample.png
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage01.imageset/puppyImage01.png
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage02.imageset/puppyImage02.png
  walkmong/walkmong/Assets.xcassets/MatchingView/puppyImage03.imageset/puppyImage03.png
  walkmong/walkmong/Assets.xcassets/MatchingView/sampleImage.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/sampleImage.imageset/sampleImage.png
  walkmong/walkmong/Assets.xcassets/MatchingView/scheduleIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/scheduleIcon.imageset/scheduleIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/starIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/starIcon.imageset/starIcon.svg
  walkmong/walkmong/Assets.xcassets/MatchingView/walkItems.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MatchingView/walkItems.imageset/walkItems.svg
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/BaseViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/DogInformation.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CustomNavigationBar.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkInfoView.swift
  walkmong/walkmong/SceneDelegate.swift
Labels: Design 🎨

#41 [Design] DogProfileViewController 구현
  walkmong/walkmong/Assets.xcassets/MyPage/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/VaccinationCompletedIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/VaccinationCompletedIcon.imageset/VaccinationCompletedIcon.svg
  walkmong/walkmong/Assets.xcassets/MyPage/VaccinationIncompleteIcon.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MyPage/VaccinationIncompleteIcon.imageset/VaccinationIncompleteIcon.svg
  walkmong/walkmong/MatchingApplyProcedure/Models/DogProfile.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Controllers/EditDogOwnershipViewController.swift
  walkmong/walkmong/Mypage/Controllers/EditWalkerProfileViewController.swift
  walkmong/walkmong/Mypage/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Views/BasicInfoView.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
  walkmong/walkmong/Mypage/Views/SocialInfoView.swift
  walkmong/walkmong/Mypage/Views/VaccinationView.swift
Labels: Design 🎨

#42 [Fix] 디자이너 수정사항 반영
  walkmong/walkmong/Extension/NavigationBar.swift
  walkmong/walkmong/MainTabBarController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/BaseViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CustomNavigationBar.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkInfoView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
Labels: Fix 🔨

#43 [Fix] MatchingFilterView에 "산책이 가능한 견종을 모두 선택해주세요." 추가
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
Labels: Fix 🔨

#45 [Feat/Design] 만남 장소 맵 UI 구현
  walkmong/walkmong/Assets.xcassets/MapView/LocationIconMainBlue.imageset/Contents.json
  walkmong/walkmong/Assets.xcassets/MapView/LocationIconMainBlue.imageset/LocationIconMainBlue.svg
  walkmong/walkmong/Extension/UITextField+.swift
  walkmong/walkmong/Extension/UIViewController+.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyDetailSelectModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyMapModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapAddressModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapNotifyModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyPlaceSearchView.swift
  walkmong/walkmong/Network/GeocodingAPIManager.swift
  walkmong/walkmong/Network/ReverseGeocodingAPIManager.swift
Labels: Feature ✨, Design 🎨

#47 [Design/Feat] 산책 지원 - 전달 메세지 UI 구현
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong/Extension/NavigationBar.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMessageViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMessageView.swift
Labels: Feature ✨, Design 🎨

#49 [Refactor] 모델 및 네트워크 매니저 리팩토링 - 재선언 및 타입 모호성 문제 해결
  walkmong/walkmong/MatchingApplyProcedure/Models/BroadAPI.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingData.swift
  walkmong/walkmong/Network/APIResponse.swift
  walkmong/walkmong/Network/NetworkManager.swift
Labels: Fix 🔨

#53 [Hotfix] 탭바 숨김 처리
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
Labels: Hotfix 🚨

#54 [Feat] MatchingDogInformationViewController mock서버 연결
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/BoardDetail.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/BroadAPI.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkInfoView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Network/NetworkManager.swift
Labels: Feature ✨

#55 [Feat] dogprofilevc 데이터 연결
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Models/DogAPI.swift
  walkmong/walkmong/Mypage/Models/DogProfileResponse.swift
  walkmong/walkmong/Mypage/Views/BasicInfoView.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
  walkmong/walkmong/Mypage/Views/SocialInfoView.swift
  walkmong/walkmong/Mypage/Views/VaccinationView.swift
  walkmong/walkmong/Network/NetworkManager.swift
Labels: Feature ✨

#57 [Feat] 데이터 흐름 연결
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingData.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/CalendarView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
Labels: Feature ✨

#58 [Fix] 디자이너 UI 수정사항 반영
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingCell.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
Labels: Fix 🔨

#59 [Feat] 장소 선택 데이터 UI 반영 로직 구현
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyDetailSelectModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyFinalModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyMapModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyMessageModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapAddressModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMessageView.swift
Labels: Feature ✨, Fix 🔨, Design 🎨

#60 [Feat] 지도 검색 결과 구현
  .gitignore
  walkmong/.gitignore
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyMapViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingApplyPlaceSearchViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/GeocodingModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingApplyPlaceSearchModel.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyPlaceSearchView.swift
  walkmong/walkmong/Network/GeocodingAPIManager.swift
Labels: Feature ✨, Chore 📂

#62 [Fix] server change
  walkmong/walkmong/Info.plist
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/BoardDetail.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/BroadAPI.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingData.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
Labels: Fix 🔨

#64 [Chore] mock 데이터 삽입
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Models/MatchingData.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/DropdownView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingApplyMapAddressModalView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/OwnerInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/ProfileView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Network/NetworkManager.swift
Labels: Chore 📂

#65 [Fix] Modify design
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/100.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/1024.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/114.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/120.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/128.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/144.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/152.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/16.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/167.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/172.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/180.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/196.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/20.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/216.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/256.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/29.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/32.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/40.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/48.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/50.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/512.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/55.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/57.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/58.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/60.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/64.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/66.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/72.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/76.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/80.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/87.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/88.png
  walkmong/walkmong/Assets.xcassets/AppIcon.appiconset/92.png
  walkmong/walkmong/Assets.xcassets/MatchingView/selectdongbtn.imageset/selectdongbtn.svg
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingDogInformationViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Controllers/MatchingViewController.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/FilterSelectView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingDogInformationView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingFilterView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/MatchingView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/RelatedInfoView.swift
  walkmong/walkmong/MatchingApplyProcedure/Views/WalkInfoView.swift
  walkmong/walkmong/Mypage/Controllers/DogProfileViewController.swift
  walkmong/walkmong/Mypage/Views/DogProfileView.swift
Labels: Fix 🔨
