Repository jullaene/walkmong_front, pull requests merged in 2025-01, with the labels that each got.

#126 [Feat] splash&onboarding 구현
  walkmong/walkmong/Application/SceneDelegate.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration1.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration1.imageset/onboardingIllustration1.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration2.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration2.imageset/onboardingIllustration2.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration3.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration3.imageset/onboardingIllustration3.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration4.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/onboardingIllustration4.imageset/onboardingIllustration4.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashIllustration.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashIllustration.imageset/splashIllustration.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashLogo.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashLogo.imageset/splashLogo.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashText.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashText.imageset/splashText.svg
  walkmong/walkmong/Presentation/Splash&Onboarding/Onboarding/ViewController/OnboardingViewController.swift
  walkmong/walkmong/Presentation/Splash&Onboarding/Onboarding/Views/OnboardingView.swift
  walkmong/walkmong/Presentation/Splash&Onboarding/Splash/ViewController/SplashViewController.swift
  walkmong/walkmong/Presentation/Splash&Onboarding/Splash/Views/SplashView.swift
Labels: Feature ✨, Design 🎨

#130 [Feat] 채팅 STOMP/HTTP API 연동 및 UI 컴포넌트 구조 수정
  walkmong/Podfile
  walkmong/Podfile.lock
  walkmong/walkmong.xcodeproj/xcshareddata/xcschemes/walkmong.xcscheme
  walkmong/walkmong/Application/Info.plist
  walkmong/walkmong/Global/Components/MatchingState.swift
  walkmong/walkmong/Global/Constants/Record.swift
  walkmong/walkmong/Global/Constants/Status.swift
  walkmong/walkmong/Global/Extension/Date+.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/IsWalkerIcon.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/WalkTalk/IsWalkerIcon.imageset/Ellipse 324.png
  walkmong/walkmong/Network/API/WalktalkAPI.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Response/APIResponse.swift
  walkmong/walkmong/Network/Response/MessageSendModel.swift
  walkmong/walkmong/Network/Response/WalktalkResponse.swift
  walkmong/walkmong/Network/Service/StompService.swift
  walkmong/walkmong/Network/Service/WalktalkService.swift
  walkmong/walkmong/Presentation/AlertView/CustomAlertViewController.swift
  walkmong/walkmong/Presentation/MainTabBar/MainTabBarController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Models/WalkTalkChatLogModel.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/ViewController/WalktalkChatViewController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatUpperView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatView.swift
  walkmong/walkmong/Presentation/Walktalk/List/Models/WalktalkListModel.swift
  walkmong/walkmong/Presentation/Walktalk/List/ViewController/WalktalkListViewController.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListMatchingCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListPageCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListView.swift
Labels: Feature ✨, Fix 🔨, Chore 📂, Refactor

#138 [Feat] review UI
  walkmong/walkmong/Global/Components/CharacterCountManager.swift
  walkmong/walkmong/Global/Components/KeyboardEventManager.swift
  walkmong/walkmong/Global/Extension/UIButton+.swift
  walkmong/walkmong/Global/Extension/UIViewController+.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/MainColor/buttonBad.colorset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/cameraIcon.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/cameraIcon.imageset/cameraIcon.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/deleteImageBtn.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/deleteImageBtn.imageset/deleteImageBtn.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/reviewLikeIcon.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/reviewLikeIcon.imageset/reviewLikeIcon.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/reviewLikeSelectedIcon.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/reviewLikeSelectedIcon.imageset/reviewLikeSelectedIcon.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/starIcon.imageset/starIcon.svg
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/starIcon_gray200.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/MatchingView/starIcon_gray200.imageset/starIcon_gray200.svg
  walkmong/walkmong/Network/API/ReviewAPI.swift
  walkmong/walkmong/Network/Response/APIResponse.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Models/Hashtag.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/ViewController/PetOwnerDetailReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Views/DetailReviewHashtagView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Views/PetOwnerDetailReviewView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Views/ReviewPhotoView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerReview/ViewController/PetOwnerReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerReview/Views/PetOwnerReviewView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerReview/Views/RatingQuestionView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkerReview/ViewController/WalkerReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkerReview/Views/WalkerReviewView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageReviewView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageView.swift
Labels: Feature ✨

#143 [Design] 반려견 경험 입력 페이지 UI 구현
  walkmong/walkmong/Application/SceneDelegate.swift
  walkmong/walkmong/Global/Components/CountingTextView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/Introduction/ViewController/MatchingApplyFirstIntroductionViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/Introduction/Views/MatchingApplyFirstApplyIntroductionView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetExperience/ViewController/MatchingApplyPetExperienceViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetExperience/Views/MatchingApplyPetExperienceView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetWalkExperience/ViewController/MatchingApplyPetWalkExperienceViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetWalkExperience/Views/MatchingApplyPetWalkExperienceView.swift
Labels: Design 🎨

#145 [Feat] api connect
  walkmong/walkmong/Global/Extension/String+.swift
  walkmong/walkmong/Network/API/BoardAPI.swift
  walkmong/walkmong/Network/API/MemberAPI.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Foundation/NetworkProvider.swift
  walkmong/walkmong/Network/Response/BoardListResponse.swift
  walkmong/walkmong/Network/Response/DogListResponse.swift
  walkmong/walkmong/Network/Response/MemberWalkingResponse.swift
  walkmong/walkmong/Network/Service/BoardService.swift
  walkmong/walkmong/Network/Service/MemberService.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/ProfileView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/ViewController/MatchingViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingCell.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Basic/ViewController/MatchingApplyWalkRequestViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/DogProfileSelection/Views/MatchingApplyWalkRequestDogProfileSelectionView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/InformationInput/Views/MatchingApplyWalkRequestInformationInputView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/ViewController/MyPageViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageContentViewSection.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPagePetView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageProfileView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageReviewView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageWalkInfoView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/PetProfileCell.swift
Labels: Feature ✨

#149 fix: 병합 문제로 생긴 문제 해결
  walkmong/walkmong/Global/Extension/UIImage+.swift
  walkmong/walkmong/Network/Response/MemberWalkingResponse.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/ViewController/MatchingStatusApplicantDetailViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/Views/MatchingStatusApplicantDetailView.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantList/ViewController/MatchingStatusApplicantListViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantList/Views/MatchingStatusApplicantListView.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/ViewController/MatchingStatusMyApplicationViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/Views/MatchingStatusMyApplicationView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/ViewController/MatchingStatusWalkInfoForOwnerViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/Views/MatchingStatusWalkInfoForOwnerView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/ViewController/MatchingStatusWalkInfoForWalkerViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/Views/MatchingStatusWalkInfoForWalkerView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageReviewView.swift
Labels: Hotfix 🚨

#158 [Design] 반려견 정보 입력 페이지 UI 구현
  walkmong/walkmong/Global/Components/CountingTextView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/Introduction/Views/MatchingApplyFirstApplyIntroductionView.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/ViewController/RegisterPetInfoViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/Views/RegisterPetInfoView.swift
  walkmong/walkmong/Presentation/RegisterPet/Message/ViewController/RegisterPetMessageViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Message/Views/RegisterPetMessageView.swift
  walkmong/walkmong/Presentation/RegisterPet/Sociality/ViewController/RegisterPetSocialityViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Sociality/Views/RegisterPetSocialityView.swift
Labels: Design 🎨

#161 [Feat] 반려견 정보 입력 페이지 API 연동
  walkmong/walkmong/Network/API/DogAPI.swift
  walkmong/walkmong/Network/Foundation/APIEndpoint.swift
  walkmong/walkmong/Network/Request/PostDogInfoRequest.swift
  walkmong/walkmong/Network/Service/DogService.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/ViewController/RegisterPetInfoViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/Views/RegisterPetInfoView.swift
  walkmong/walkmong/Presentation/RegisterPet/Message/ViewController/RegisterPetMessageViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Message/Views/RegisterPetMessageView.swift
  walkmong/walkmong/Presentation/RegisterPet/Sociality/ViewController/RegisterPetSocialityViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Sociality/Views/RegisterPetSocialityView.swift
Labels: Feature ✨

#160 [Feat] 게시글 작성 api connect
  walkmong/walkmong/Global/Extension/UIViewController+.swift
  walkmong/walkmong/Network/API/BoardAPI.swift
  walkmong/walkmong/Network/Response/AddressListResponse.swift
  walkmong/walkmong/Network/Response/BoardRegisterResponse.swift
  walkmong/walkmong/Network/Response/DogInfoResponse.swift
  walkmong/walkmong/Network/Service/BoardService.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/Views/MatchingProfileInformationView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Models/AddressModel.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/ViewController/MatchingViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/CalendarView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/DropdownView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/FilterSelectView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingCell.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Basic/ViewController/MatchingApplyWalkRequestViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Basic/Views/MatchingApplyWalkRequestView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Caution/ViewController/MatchingApplyWalkRequestCautionViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/DogProfileSelection/ViewController/MatchingApplyWalkRequestDogProfileSelectionViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/DogProfileSelection/Views/MatchingApplyWalkRequestDogProfileSelectionView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/InformationInput/ViewController/MatchingApplyWalkRequestInformationInputViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/InformationInput/Views/MatchingApplyWalkRequestInformationInputView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Summarize/ViewController/MatchingApplyWalkRequestViewSummarizeViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Summarize/Views/MatchingApplyWalkRequestViewSummarizeView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/TextInput/ViewController/MatchingApplyWalkRequestTextInputViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/TextInput/Views/MatchingApplyWalkRequestTextInputView.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/Views/MatchingStatusApplicantDetailView.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantList/Views/MatchingStatusApplicantListView.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/Views/MatchingStatusMyApplicationView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/Views/MatchingStatusWalkInfoForOwnerView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/Views/MatchingStatusWalkInfoForWalkerView.swift
Labels: Feature ✨

#157 [Design] 산책 정보 페이지 맵뷰 추가
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/Views/MatchingStatusWalkInfoForOwnerView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/Views/MatchingStatusWalkInfoForWalkerView.swift
Labels: Design 🎨

#165 [Feat] api connect
  walkmong/walkmong/Global/Extension/Date+.swift
  walkmong/walkmong/Global/Extension/String+.swift
  walkmong/walkmong/Network/API/BoardAPI.swift
  walkmong/walkmong/Network/Response/BoardDetailAPI.swift
  walkmong/walkmong/Network/Response/BoardListResponse.swift
  walkmong/walkmong/Network/Service/BoardService.swift
  walkmong/walkmong/Presentation/MainTabBar/MainTabBarController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/MatchingDogInformationView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/ViewController/MatchingViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/CalendarView.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingCell.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Caution/ViewController/MatchingApplyWalkRequestCautionViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/Views/MatchingStatusApplicantDetailView.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantList/Views/MatchingStatusApplicantListView.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/Views/MatchingStatusMyApplicationView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/Views/MatchingStatusWalkInfoForOwnerView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/Views/MatchingStatusWalkInfoForWalkerView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/PetProfileCell.swift
Labels: Fix 🔨

#166 [Feat] 산책 지원 로직 데이터 연결 및 API 연동
  walkmong/walkmong/Network/API/ApplyAPI.swift
  walkmong/walkmong/Network/Request/MatchingApplyRequest.swift
  walkmong/walkmong/Network/Service/ApplyService.swift
  walkmong/walkmong/Presentation/MatchingApply/DetailSelect/ViewController/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/ViewController/MatchingApplyFinalViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/Views/MatchingApplyFinalView.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/Views/MatchingProfileInformationView.swift
  walkmong/walkmong/Presentation/MatchingApply/Message/ViewController/MatchingApplyMessageViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Message/Views/MatchingApplyMessageView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Summarize/Views/MatchingApplyWalkRequestViewSummarizeView.swift
Labels: Feature ✨

#168 [Feat] 매칭 현황 탭 API 연동
  walkmong/walkmong/Global/Constants/Record.swift
  walkmong/walkmong/Global/Constants/Status.swift
  walkmong/walkmong/Network/API/ApplyAPI.swift
  walkmong/walkmong/Network/Foundation/NetworkProvider.swift
  walkmong/walkmong/Network/Response/GetApplyHistoryResponse.swift
  walkmong/walkmong/Network/Service/ApplyService.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/ViewController/MatchingStatusListViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/Views/MatchingStatusListCollectionViewCell.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/Views/MatchingStatusListPageCollectionViewCell.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/Views/MatchingStatusListView.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/ViewController/WalktalkChatViewController.swift
  walkmong/walkmong/Presentation/Walktalk/Chat/Views/WalktalkChatUpperView.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListCollectionViewCell.swift
  walkmong/walkmong/Presentation/Walktalk/List/Views/WalktalkListView.swift
Labels: Feature ✨

#169 [Feat] api connect
  walkmong/walkmong/Global/Extension/Date+.swift
  walkmong/walkmong/Network/API/BoardAPI.swift
  walkmong/walkmong/Network/API/MemberAPI.swift
  walkmong/walkmong/Network/API/ReviewAPI.swift
  walkmong/walkmong/Network/Response/BoardDetailResponse.swift
  walkmong/walkmong/Network/Response/DogInfoResponse.swift
  walkmong/walkmong/Network/Response/MemberWalkingResponse.swift
  walkmong/walkmong/Network/Response/ReviewToWalkerListResponse.swift
  walkmong/walkmong/Network/Service/BoardService.swift
  walkmong/walkmong/Network/Service/MemberService.swift
  walkmong/walkmong/Network/Service/ReviewService.swift
  walkmong/walkmong/Presentation/MainTabBar/MainTabBarController.swift
  walkmong/walkmong/Presentation/MatchingApply/DetailSelect/ViewController/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/MatchingDogInformationView.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/OwnerInfoView.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/ProfileView.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/RelatedInfoView.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/Views/WalkInfoView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetExperience/ViewController/MatchingApplyPetExperienceViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingCell.swift
  walkmong/walkmong/Presentation/MatchingApply/Matching/Views/MatchingView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Models/Hashtag.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Views/PetOwnerDetailReviewView.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerReview/ViewController/PetOwnerReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Caution/Views/MatchingApplyWalkRequestCautionView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/Summarize/ViewController/MatchingApplyWalkRequestViewSummarizeViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/TextInput/Views/MatchingApplyWalkRequestTextInputView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Models/CircleTagView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Models/DogReviewModel.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/ViewController/WalkReviewViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/ProfileFrameView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewCell.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkReview/Views/WalkReviewFrame.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/Models/DogProfile.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/ViewController/DogProfileViewController.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/Views/BasicInfoView.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/Views/DogProfileView.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/Views/SocialInfoView.swift
  walkmong/walkmong/Presentation/MyPage/DogProfile/Views/VaccinationView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/ViewController/MyPageViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/CustomRadarChartView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageReviewView.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/PetProfileCell.swift
  walkmong/walkmong/Presentation/MyPage/MyPageOwnerReview/ViewController/MyPageOwnerReviewViewController.swift
Labels: Feature ✨

#170 [Design] 실시간 위치 공유 페이지 UI 구현
  walkmong/walkmong.xcodeproj/project.pbxproj
  walkmong/walkmong/Global/Components/NavigationBar.swift
  walkmong/walkmong/Global/Resources/Assets.xcassets/LiveMap/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/LiveMap/currentLocationIcon.imageset/Contents.json
  walkmong/walkmong/Global/Resources/Assets.xcassets/LiveMap/currentLocationIcon.imageset/currentLocationIcon.svg
  walkmong/walkmong/Presentation/MatchingStatus/LiveMap/ViewController/MatchingStatusLiveMapViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/LiveMap/Views/MatchingStatusLiveMapButtonView.swift
  walkmong/walkmong/Presentation/MatchingStatus/LiveMap/Views/MatchingStatusLiveMapModalViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/LiveMap/Views/MatchingStatusLiveMapView.swift
Labels: Design 🎨

#172 [Fix] 산책 지원 로직 API / UI 및 회원가입 로직 API 디버깅
  walkmong/walkmong/Application/SceneDelegate.swift
  walkmong/walkmong/Global/Extension/UIView+.swift
  walkmong/walkmong/Network/Foundation/NetworkProvider.swift
  walkmong/walkmong/Network/Manager/AuthManager.swift
  walkmong/walkmong/Network/Response/APIResponse.swift
  walkmong/walkmong/Network/Service/ApplyService.swift
  walkmong/walkmong/Network/Service/AuthService.swift
  walkmong/walkmong/Network/Service/MemberService.swift
  walkmong/walkmong/Presentation/Login/ViewController/LoginViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DetailSelect/ViewController/MatchingApplyDetailSelectViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/DetailSelect/Views/MatchingApplyDetailSelectView.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/ViewController/MatchingApplyFinalViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/Final/Views/MatchingApplyFinalView.swift
  walkmong/walkmong/Presentation/MatchingApply/Map/Models/MatchingApplyMapModel.swift
  walkmong/walkmong/Presentation/Signup/ProfileImage/ViewController/SignupProfileImageViewController.swift
Labels: Fix 🔨

#176 [feat] 로그아웃 버튼 및 기능 구현
  walkmong/walkmong/Presentation/MyPage/MyPage/ViewController/MyPageViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/Views/MyPageSettingsView.swift
Labels: Hotfix 🚨

#178 Fix/modify UI
  walkmong/walkmong/Global/Resources/Assets.xcassets/Illustration/splashIllustration.imageset/Contents.json
  walkmong/walkmong/Presentation/MainTabBar/MainTabBarController.swift
  walkmong/walkmong/Presentation/MatchingApply/PetOwnerDetailReview/Views/PetOwnerDetailReviewView.swift
  walkmong/walkmong/Presentation/MatchingApply/WalkRequest/TextInput/Views/MatchingApplyWalkRequestTextInputView.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantList/ViewController/MatchingStatusApplicantListViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/ViewController/MatchingStatusListViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/ViewController/MatchingStatusMyApplicationViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/ViewController/MatchingStatusWalkInfoForOwnerViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/ViewController/MatchingStatusWalkInfoForWalkerViewController.swift
  walkmong/walkmong/Presentation/MyPage/MyPage/ViewController/MyPageViewController.swift
  walkmong/walkmong/Presentation/Signup/Detail/Views/SignupDetailView.swift
  walkmong/walkmong/Presentation/Splash&Onboarding/Splash/Views/SplashView.swift
Labels: Fix 🔨

#182 [Fix] 반려견 프로필 / 산책자 프로필 등록 API 구현 및 수정
  walkmong/walkmong/Network/API/MemberAPI.swift
  walkmong/walkmong/Network/Request/PostDogExperienceRequest.swift
  walkmong/walkmong/Network/Request/PostDogInfoRequest.swift
  walkmong/walkmong/Network/Service/DogService.swift
  walkmong/walkmong/Network/Service/MemberService.swift
  walkmong/walkmong/Presentation/MatchingApply/DogInformation/ViewControler/MatchingDogInformationViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/Introduction/ViewController/MatchingApplyFirstIntroductionViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetExperience/ViewController/MatchingApplyPetExperienceViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetExperience/Views/MatchingApplyPetExperienceView.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetWalkExperience/ViewController/MatchingApplyPetWalkExperienceViewController.swift
  walkmong/walkmong/Presentation/MatchingApply/FirstApply/PetWalkExperience/Views/MatchingApplyPetWalkExperienceView.swift
  walkmong/walkmong/Presentation/MatchingStatus/List/ViewController/MatchingStatusListViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/ViewController/RegisterPetInfoViewController.swift
  walkmong/walkmong/Presentation/RegisterPet/Info/Views/RegisterPetInfoView.swift
  walkmong/walkmong/Presentation/RegisterPet/Message/ViewController/RegisterPetMessageViewController.swift
Labels: Fix 🔨

#187 [Feat] 매칭 상세 하단 버튼 구현
  walkmong/walkmong/Global/Extension/UIViewController+.swift
  walkmong/walkmong/Network/Response/WalktalkResponse.swift
  walkmong/walkmong/Network/Service/ApplyService.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/ViewController/MatchingStatusApplicantDetailViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/ApplicantDetail/Views/MatchingStatusApplicantDetailView.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/ViewController/MatchingStatusMyApplicationViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/MyApplication/Views/MatchingStatusMyApplicationView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/ViewController/MatchingStatusWalkInfoForOwnerViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForOwner/Views/MatchingStatusWalkInfoForOwnerView.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/ViewController/MatchingStatusWalkInfoForWalkerViewController.swift
  walkmong/walkmong/Presentation/MatchingStatus/WalkInfoForWalker/Views/MatchingStatusWalkInfoForWalkerView.swift
  walkmong/walkmong/Presentation/Walktalk/List/ViewController/WalktalkListViewController.swift
Labels: Feature ✨
